name: CI

on:
  push:
    branches:
      - develop

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Install yarn # https://github.com/actions/setup-node/issues/182
        run: |-
          curl -fsSL --create-dirs -o $HOME/bin/yarn \
          https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn-1.22.19.js
          chmod +x $HOME/bin/yarn
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Setup yarn version
        run: corepack enable && yarn set version 3.6.4 && yarn plugin import interactive-tools
      - name: Install yarn dependencies
        run: yarn install --silent --inline-builds --network-timeout 600000
      - name: Build
        run: yarn tsc

      - name: Login to npm
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # Add your NPM token as a secret in GitHub repository settings

      - name: Publish to npm
        run: npm publish --access public  # Adjust access level if necessary

